// GENERATED by scripts/fetch-snapshot.mjs at build time — do not hand-edit.
<<<<<<< HEAD
// Fetched 2 Oct 2026, 00:02 UTC from open.er-api.com (the exact feed the converter's client
=======
// Fetched 30 Sept 2026, 00:02 UTC from open.er-api.com (the exact feed the converter's client
>>>>>>> parent of 9cea4d4 (feat(design): Rung R2 — The Control Law (v0.7.1))
// script refreshes from), Coinbase spot + gold-api for the ticker pairs.
// The static render is this snapshot; browser scripts swap it for live values
// within ~1s (8s timeout; on failure the snapshot below stands, honestly
// stamped).
export interface FxSnapshot {
  ok: boolean;
  rates: Record<string, number>;
  as_of: string;
  cached: boolean;
}

export const FX_SNAPSHOT: FxSnapshot = {
  ok: true,
  rates: {
    "USD": 1,
<<<<<<< HEAD
    "NGN": 1327.682521,
    "GBP": 0.757129,
    "EUR": 0.88731,
    "CAD": 1.423249,
    "AED": 3.6725,
    "SAR": 3.75,
    "GHS": 11.731372,
    "XOF": 582.012062,
    "XAF": 582.012062,
    "CNY": 6.714553,
    "JPY": 157.92293,
    "INR": 96.378852,
    "KES": 129.630371,
    "EGP": 52.300596,
    "ZAR": 16.665706
  },
  as_of: "2 Oct 2026, 00:02 UTC",
=======
    "NGN": 1327.241555,
    "GBP": 0.755961,
    "EUR": 0.88152,
    "CAD": 1.418513,
    "AED": 3.6725,
    "SAR": 3.75,
    "GHS": 11.701151,
    "XOF": 578.234411,
    "XAF": 578.234411,
    "CNY": 6.717859,
    "JPY": 157.389062,
    "INR": 96.063464,
    "KES": 129.679115,
    "EGP": 52.092039,
    "ZAR": 16.40694
  },
  as_of: "30 Sept 2026, 00:02 UTC",
>>>>>>> parent of 9cea4d4 (feat(design): Rung R2 — The Control Law (v0.7.1))
  cached: false,
};

export const FX_SNAPSHOT_LABEL = "live at build — refreshes in your browser";

// Unix seconds of the feed's own stamp; ticker-live.js skips the network
// only within 60s of it (a static build is always older, so visitors get a
// live refresh while crawlers see the truthful build-time figures).
<<<<<<< HEAD
export const FX_SNAPSHOT_TS = 1790899351;
=======
export const FX_SNAPSHOT_TS = 1790726551;
>>>>>>> parent of 9cea4d4 (feat(design): Rung R2 — The Control Law (v0.7.1))
