// GENERATED by scripts/fetch-snapshot.mjs at build time — do not hand-edit.
// Fetched 1 Oct 2026, 00:02 UTC from open.er-api.com (the exact feed the converter's client
// script refreshes from), Coinbase spot + gold-api for the ticker pairs.
// The static render is this snapshot; browser scripts swap it for live values
// within ~1s (8s timeout; on failure the snapshot below stands, honestly
// stamped).
export interface FxSnapshot {
  ok: boolean;
  rates: Record<string, number>;
  as_of: string;
  cached: boolean;
}

export const FX_SNAPSHOT: FxSnapshot = {
  ok: true,
  rates: {
    "USD": 1,
    "NGN": 1328.645734,
    "GBP": 0.753798,
    "EUR": 0.881813,
    "CAD": 1.421278,
    "AED": 3.6725,
    "SAR": 3.75,
    "GHS": 11.706717,
    "XOF": 578.339132,
    "XAF": 578.339132,
    "CNY": 6.716878,
    "JPY": 157.298282,
    "INR": 95.997282,
    "KES": 129.700459,
    "EGP": 51.965687,
    "ZAR": 16.415882
  },
  as_of: "1 Oct 2026, 00:02 UTC",
  cached: false,
};

export const FX_SNAPSHOT_LABEL = "live at build — refreshes in your browser";

// Unix seconds of the feed's own stamp; ticker-live.js skips the network
// only within 60s of it (a static build is always older, so visitors get a
// live refresh while crawlers see the truthful build-time figures).
export const FX_SNAPSHOT_TS = 1790812951;
