// GENERATED by scripts/fetch-snapshot.mjs at build time — do not hand-edit.
// Fetched 7 Oct 2026, 00:02 UTC from open.er-api.com (the exact feed the converter's client
// script refreshes from), Coinbase spot + gold-api for the ticker pairs.
// The static render is this snapshot; browser scripts swap it for live values
// within ~1s (8s timeout; on failure the snapshot below stands, honestly
// stamped).
export interface FxSnapshot {
  ok: boolean;
  rates: Record<string, number>;
  as_of: string;
  cached: boolean;
}

export const FX_SNAPSHOT: FxSnapshot = {
  ok: true,
  rates: {
    "USD": 1,
    "NGN": 1328.1192,
    "GBP": 0.753989,
    "EUR": 0.888741,
    "CAD": 1.422126,
    "AED": 3.6725,
    "SAR": 3.75,
    "GHS": 11.622419,
    "XOF": 582.979097,
    "XAF": 582.979097,
    "CNY": 6.711932,
    "JPY": 158.145386,
    "INR": 96.46757,
    "KES": 129.556657,
    "EGP": 52.305619,
    "ZAR": 16.534158
  },
  as_of: "7 Oct 2026, 00:02 UTC",
  cached: false,
};

export const FX_SNAPSHOT_LABEL = "live at build — refreshes in your browser";

// Unix seconds of the feed's own stamp; ticker-live.js skips the network
// only within 60s of it (a static build is always older, so visitors get a
// live refresh while crawlers see the truthful build-time figures).
export const FX_SNAPSHOT_TS = 1791331352;
